In [1]:
import numpy as np 

In [14]:
lst = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

arr = np.array(lst)
print(arr)

print(arr*4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

print(np.argmin(arr))
print(np.argmax(arr))
print(arr[np.argmin(arr)])
print(arr[np.argmax(arr)])

print(np.min(arr))
print(np.max(arr)) #Yes, they match

new_arr = arr[arr > 20]
print(new_arr)

[20 27  9 12 31 17  4 50 39 35]
[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
6
7
4
50
4
50
[27 31 50 39 35]


In [36]:
import numpy as np

matrix = np.array([
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
])

print(matrix)

print(matrix.shape)
print(matrix[:, 2])
print(matrix[1])
print(matrix * 2)
print(np.mean(matrix, axis=0))
print(np.mean(matrix))
print(np.max(matrix, axis=1))
print(np.min(matrix, axis=0))

flat = matrix.flatten()
print(flat)
print(flat.shape) #Becomes 1D array 

print(np.argmin(matrix))
print(np.argmax(matrix))

print(np.unravel_index(np.argmin(matrix), matrix.shape))
print(np.unravel_index(np.argmax(matrix), matrix.shape))

matrix > 15

print(np.sort(matrix, axis=None))

[[ 5 12 17  9]
 [ 8 21 14  3]
 [ 6 13 19 11]]
(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
(12,)
7
5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
[ 3  5  6  8  9 11 12 13 14 17 19 21]


In [39]:
import numpy as np

arr = np.array([
    [2, 3, 5],
    [14, 6, 8], 
    [11, 13, 17], 
    [7, 10, 13]
]) 

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def rows_with_prime_number(arr):
    result = []

    for row in arr:
        for value in row:
            if is_prime(value):
                result.append(row)
                break 
    return np.array(result)

print(rows_with_prime_number(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [43]:
import numpy as np 

def checkerboard():
    board = np.zeros((8, 8), dtype=int)

    board[0::2, ::2] = 1
    board[1::2, 1::2] = 1

    return board

print(checkerboard())

def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)

    board[0::2, 1::2] = 1
    board[1::2, ::2] = 1

    return board 

print(reverse_checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [51]:
import numpy as np 

def expansion(arr, n):
    spaces = " " * n
    expanded = []

    for word in arr:
        expanded_word = spaces.join(list(word))
        expanded.append(expanded_word)

    return np.array(expanded)

alien_language = np.array(['@*%$%&', '*@^*(#)#'])
print(expansion(alien_language, 1))
print(expansion(alien_language, 3))

['@ * % $ % &' '* @ ^ * ( # ) #']
['@   *   %   $   %   &' '*   @   ^   *   (   #   )   #']


In [53]:
import numpy as np

np.random.seed(246)
stars = np.random.randint(500, 2000, (5,5))

def secondDimmest(arr):
    sorted_rows = np.sort(arr, axis=1)
    return sorted_rows[:, -2]

print(secondDimmest(stars))

[1378 1644 1717 1252 1708]
